# mava/configs/network/job_shop_network.yaml
_name_: job_shop_network
defaults:
  - _self_

# JobShop specific parameters
num_actions: ${eval:'${env.scenario.task_config.num_machines} * (${env.scenario.task_config.num_jobs} + 1)'}  # 4 * (5 + 1) = 24

# --- Actor network ------------------------------------------------------------
actor_network:
  _target_: mava.networks.job_shop_network.JobShopActor
  num_actions: ${network.num_actions}

# --- Critic network -----------------------------------------------------------
critic_network:
  _target_: mava.networks.job_shop_network.JobShopCritic

# --- For compatibility with existing Mava code --------------------------------
action_dim: ${network.num_actions}