defaults:
  - logger: logger
  - arch: anakin
  - system: ppo/ff_ippo
  - network: job_shop_network # mlp  # [mlp, cnn]
  - env: job_shop # rware  # [cleaner, connector, vector-connector, gigastep, lbf, mabrax, matrax, rware, smax, mpe]
  - _self_

hydra:
  searchpath:
    - file://mava/configs
